version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: "amqp://admin:admin123@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
